language: node_js
node_js:
- "8"
- "10"
- "12"
branches:
  only:
  - master
  - development
  - /^release-v.*$/ # this should check release-v* branches
script:
- npm install -g grunt-cli
- npm install
- node_modules/bower/bin/bower install
- cd bower_components/angularjs-slider && npm install && cd ../..
- cat bower_components/angularjs-slider/Gruntfile.js
- cp Gruntfile.default.js Gruntfile.js
- node_modules/.bin/grunt ci
